name: Terraform Plan

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      #- name: Terraform Format
      #  run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out "tf_plan" 
        
      - name: Upload TF Plan
        uses: actions/upload-artifact@v2
        with:
          name: tf_plan
          path: ./examples/tf_plan
          if-no-files-found: error
          retention-days: 1
   
  terraform_apply:
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    #environment:
     #  name: tf_apply
    
    steps:
    
      - name: Download TF Plan
        uses: actions/download-artifact@v2
        with:
          name: tf_plan
          path: ./examples
      - name: Terraform Apply
        run: terraform apply -auto-approve "tf_plan"

